### ISSUE TITLE
Cannot load okta login page

### ISSUE THREAD

**Issue by ALMLAMBO** [okta/okta-sdk-dotnet#359]
Hi, 
I was following okta developer guide for external authentication [https://developer.okta.com/blog/2019/10/16/csharp-blazor-authentication](https://developer.okta.com/blog/2019/10/16/csharp-blazor-authentication), but when I test the app, I saw sorry there is nothing on this address and throws an exception that message.state is null or empty.

**Comment by laura-rodriguez** [comment]
Hi @ALMLAMBO ,

Sorry for the inconvenience. I communicated your issue to the team in charge of our blog samples. They are already aware of this issue and will provide a solution soon. Stay tuned for updates.

**Comment by ALMLAMBO** [comment]
Hi,
I want to ask when the problem will be solved?

**Comment by laura-rodriguez** [comment]
My team doesn't own blog samples, so we don't know much about timelines. I suggest asking directly in the blog post’s comment section.

**Comment by ALMLAMBO** [comment]
I want to ask for some alternatives to okta that can be integrated into c#.

**Comment by laura-rodriguez** [comment]
Can you please clarify what you are looking for? what's your use case?

**Comment by ALMLAMBO** [comment]
My case is that I need to build a role-based login system on Blazor.

**Comment by ALMLAMBO** [comment]
Please for your fast support because it is recommended to finish the login system at 12.02.2020. 
Is it possible or no?

**Comment by laura-rodriguez** [comment]
I'm not a Blazor expert, but maybe our ASP.NET MVC samples can help you to configure Okta + OIDC:
* https://github.com/okta/samples-aspnetcore/tree/master/samples-aspnetcore-3x/okta-hosted-login
* Step-by-step instructions for this sample: https://developer.okta.com/docs/guides/sign-into-web-app/aspnetcore3/before-you-begin/

I believe the configuration you need should be the same, but you will have to take care of your Blazor components.

You don't need the `okta-sdk-dotnet` library for this since this helps developers to interact with the Okta management API, but you can use our [ASP.NET sdk](https://github.com/okta/okta-aspnet) as explained in our guides.

I hope this helps.

**Comment by laura-rodriguez** [comment]
Issue not related to the SDK.
