### ISSUE TITLE
Active Directory Import

### ISSUE THREAD

**Issue by mattmcnabb** [okta/okta-sdk-dotnet#375]
I'd like to be able to initiate an Active Directory user import using this SDK. Is that currently possible, or are there any plans to include that functionality? Thanks!

**Comment by laura-rodriguez** [comment]
Hi @mattmcnabb ,

Thanks for your question.

Okta offers some solutions for AD syncing already. Have you checked this?https://help.okta.com/en/prod/Content/Topics/Directory/ad-agent-import-users-on-demand.htm
You can reach out to your account representative to learn about other options.

While this SDK won't offer a direct AD sync solution, you can always manually post users to the Okta API with this SDK.

**Comment by mattmcnabb** [comment]
@laura-rodriguez Yes, I'm aware of the AD synchronization capabilities. What I'm actually getting at is a way to force an incremental or full import using this SDK. I'm not sure the API actually offers this capability but am hoping that it does. Currently the lowest sync interval is 1 hour and this can be a source of headaches sometimes, particularly when using AD groups for assigning access to applications in Okta.

I think there is an idea in the community portal already around forcing an import with the API, but I don't see any responses and was hoping an issue in this repo may help move that along 😄

**Comment by laura-rodriguez** [comment]
I'm not sure what you mean by community portal. Can you please send me a link?

**Comment by mattmcnabb** [comment]
@laura-rodriguez I'm referring to the Okta Ideas portal that can be found in the help and support portal.

Here's a link to the actual idea: https://ideas.okta.com/app/#/case/106630

**Comment by pheebkat** [comment]
Thx @laura-rodriguez for getting us together here! 

Hiya @mattmcnabb, you're right, the idea does need more context and votes in order to get the Okta product team to review it (ideas need at least 20 votes to get reviewed by the product team, and this one currently has 9). You can help it gain more traction by posting your comment above to the idea (_Currently the lowest sync interval is 1 hour and this can be a source of headaches sometimes, particularly when using AD groups for assigning access to applications in Okta._) You can also share the idea around to get more votes from people like you that want and need this idea! Hope this is helpful, thanks for being part of the Okta Community! 😄
