### ISSUE TITLE
Documentation page only goes to 5.1.1 but current is 7.x

### ISSUE THREAD

**Issue by rcollette** [okta/okta-sdk-dotnet#686]
### Describe the bug?

The documentation at https://developer.okta.com/okta-sdk-dotnet/latest/ appears to be missing the documentation for the V6 and V7 releases.

### What is expected to happen?

I should see at least 7.0, 7.0.1 and 7.02 versions in the dropdown, and V6 versions as well.

### What is the actual behavior?

The drop down only shows up to 5.x versions.

### Reproduction Steps?

N/A

### .NET Version

n/a

### SDK Version

7.0.2

**Comment by laura-rodriguez** [comment]
Thanks for reporting this issue. A new internal ticket has been created to be prioritized by the team.

Internal Ref: OKTA-681918

**Comment by bhavik-thakkar-okta** [comment]
Hey @rcollette , we are currently in the process of a brand refresh of our Developer Docs site and this dotnet documentation presently has been de-prioritized due to other higher priorities. As of now, we do not have a timeline of when this will be prioritized, but as soon as we have any updates, we will make sure to update you here.
